# Generated by Django 6.0.3 on 2026-03-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sessions/')),
                ('date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('available_spots', models.IntegerField(default=10)),
            ],
        ),
    ]
